name: 'Build and publish'

on:
  schedule:
    - cron: '40 13 * * 1'
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: 'Build docker image and push to Docker Hub'
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: connorlanigan/code-server-with-node:latest
